[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pddl"
dynamic = ["version"]
description = "PDDL parser"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
    {name = "Marco Favorito", email = "marco.favorito@gmail.com"},
    {name = "Francesco Fuggitti", email = "francesco.fuggitti@gmail.com"},
    {name = "Christian Muise", email = "christian.muise@queensu.ca"},
]
keywords = ["pddl"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Education",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "lark>=1.1.5,<1.2.0",
    "click>=8.1.3,<9.0.0",
]

[project.urls]
Homepage = "https://github.com/AI-Planning/pddl.git"

[project.scripts]
pddl = "pddl.__main__:cli"

[dependency-groups]
dev = [
    "pytest", "pytest-cov", "pytest-randomly", "pytest-lazy-fixtures", "tox",
    "ipython", "codecov", "black", "mypy", "flake8", "flake8-docstrings", "mkdocs",
    "markdown-include", "isort", "mistune", "mkdocs-material", "types-click",
    "vulture", "flake8-bugbear", "pymdown-extensions", "flake8-isort", "safety", "bandit",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.dynamic]
version = {attr = "pddl.__version__.__version__"}

[tool.setuptools.packages.find]
include = ["pddl*"]

[tool.setuptools.package-data]
"pddl.parser" = ["grammar.lark"]