name: docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --dev
    - name: Generate Documentation
      run: uv run tox -e docs
    - name: Deploy Documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: uv run mkdocs gh-deploy --force
