name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --dev
    - name: Unit tests and coverage
      run: |
        pyver=`echo ${{ matrix.python-version }} | tr -d "."`
        uv run tox -e py${pyver}
    - name: Upload coverage to Codecov
      if: github.actor != 'dependabot[bot]'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Generate Documentation
      run: uv run tox -e docs
